# Generated by Django 4.1.5 on 2023-01-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviebooking_created_at_moviebooking_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviebooking',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('WAITING', 'Waiting')], max_length=20),
        ),
    ]
